### ISSUE TITLE
bad kern amount

### ISSUE THREAD

**Issue by OzPineapple** [sonjiku/GFSgroff#1]
I installed the font and tried used by:

```
.ds FAM FSE

.TL
Notes
.AU
Oz
.AI
Escuela 
.Ai
Instituto 

.NH
Coeficientes de Furier

This is romatic \[u1E6C]

.EQ
a sub n = 1 over L
int from -L to L {
f(x) cos {k pi x } over L
} dx,

n ∈ ℕ
.EN
```
And compile it by 
`groff -e -Kutf8 -ms -Tps -F font n.ms > n.ps`

I got the errors

```
/usr/share/groff/1.22.4/font/devps/FSER:6736: error: bad kern amount '=30'
troff: n.ms:2: warning: can't find font 'FSER'
troff: n.ms:15: warning: can't find special character 'u0054_0323'
troff: n.ms:135: warning: can't find special character 'u2115'
```

**Comment by sonjiku** [comment]
You should check out the new commit. I believe it should fix the issue. The only thing you should change is `.ds FAM FSE` to `.ds FAM FreeSerif`.

**Comment by OzPineapple** [comment]
This shuold be this way?
```
sudo ./install.sh
cp: -r not specified; omitting directory 'Font/'
```
Any
```
Make
groff -e -K utf8 -ms -Tps -F font n.ms > n.ps
troff: n.ms:135: warning: can't find special character 'u2115'
ps2pdf n.ps n.pdf
```
![image](https://user-images.githubusercontent.com/35550219/119692326-f0954280-be10-11eb-9ec8-8eeef3a8bdeb.png)
Well it works, but is missing  the ℕ char. This normal I think, need to find a way to display unicode chars. Thanks for the help :3

**Comment by sonjiku** [comment]
> This shuold be this way?

Yes. I'm not really sure yet why it says that. It installs the fonts anyway.

> but is missing the N char

I know, as far as I know the default fonts are missing way more characters.
New commit should fixed issues with the division symbol over "cos", and also actually start using the font. I also added the other GNU Free fonts, so you can choose whichever you like.

**Comment by OzPineapple** [comment]
Jajaja I thoug that was the font. How can I query the avalible fonts?

**Comment by sonjiku** [comment]
From what I understand, by query you mean using something like `.ds fam`.
You can use:
- `.fam FreeMono` for the mono font,
- `.fam FreeSans` for the sans font, and
- `.fam FreeSerif` for the serif font.
